apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: "eks-cluster-${{values.name}}-terraform"
  namespace: flux-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  interval: 1m
  approvePlan: auto
  path: ./patterns/istio
  sourceRef:
    kind: GitRepository
    name: "eks-cluster-${{values.name}}-git-repository"
    namespace: flux-system
  vars:
    - name: aws_region
      value: ${{ values.tfVars.aws_region }}
  retryInterval: 10s
  destroyResourcesOnDeletion: true
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: aws-credentials